services:
  db:
    image: mysql:8
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: api
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: java_local
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'
